### ISSUE TITLE
Endpoints should be there for blog post links

### ISSUE THREAD

**Issue by aashish-ak** [devbae/devbae-blog#20]
**Is your feature request related to a problem? Please describe.**
Currently the links for the posts contain a `.html` extension like this:
https://devbae.tech/2020/05/01/welcome.html
Which doesn't look nice and is also unnecessarily long, it should be an endpoint like this:
https://devbae.tech/welcome
This has already been implemented in the minimal-mistakes template here in KamandPrompt blog:
http://blog.pc.iitmandi.co.in/welcome/

**Describe the solution you'd like**
One can directly make modifications by looking at the KamandPrompt [ blog repository](https://github.com/kamandprompt/blog). The code should not be blindly copied but should be well understood and minimal.

**Describe alternatives you've considered**
One can also learn about Jekyll endpoints and implement the feature himself.

**Comment by PratikshaJain37** [comment]
One solution that Jekyll has for this is to add a permalink in _config.yml:

`permalink: /:title/`

It will only display the title of the post/page, dropping the extensions and the dates

**Comment by aashish-ak** [comment]
@PratikshaJain37 It's great that you figured out the solution, would you like to open a PR on the same?
