### ISSUE TITLE
Add 'Copy to Clipboard' button to code blocks

### ISSUE THREAD

**Issue by aashish-ak** [devbae/devbae-blog#29]
**Is your feature request related to a problem? Please describe.**
Currently there is no 'Copy to clipboard' button on the code blocks, it makes it easier for users to copy the code while following the tutorials.

**Describe the solution you'd like**
A button like this should be added to the code blocks to make it easier to copy the provided code.
![Screenshot_20200618-190505__01](https://user-images.githubusercontent.com/21988675/85027310-658ae180-b197-11ea-92c2-c5c8b7593eda.jpg)

**Additional context**
You can either simply create this one yourself or can follow this [tutorial](https://www.aleksandrhovhannisyan.com/blog/dev/how-to-add-a-copy-to-clipboard-button-to-your-jekyll-blog/) to implement this.

**Comment by Signior-X** [comment]
This really looks awesome to work upon, in my app also I need this kind of thing.... Will work on this afterwards if anyone doesn't take this. Rest till then anyone if free to try this....

**Comment by aashish-ak** [comment]
@Signior-X As no one is currently working on this one, you're free to take this and work on it :)

**Comment by Signior-X** [comment]
I am working on this one.
