### ISSUE TITLE
Add a sidebar to display author profile.

### ISSUE THREAD

**Issue by aashish-ak** [devbae/devbae-blog#3]
**Is your feature request related to a problem? Please describe.**
There is no proper page to display the author profile of the author of a blog.

**Describe the solution you'd like**
Add a sidebar similar to one present in [minimal mistakes](https://github.com/mmistakes/minimal-mistakes) Jekyll theme.

![sidebar](https://user-images.githubusercontent.com/21988675/81396597-53069c80-9143-11ea-81d3-3f2052fd6c31.png)

**Additional context**
This sidebar should be added to the blog post and should contain the social links of the author.

**Comment by Signior-X** [comment]
I would like to create the sidebar to show author details, I will add the sidebar as suggested and the rest of the css. 
It would work like this, it would take the the URLs of dp instagram, github, etc of authors from the posts md file and using that it would create appropriate sidebar using the details.

**Comment by aashish-ak** [comment]
Hey @Signior-X , Glad that you're ready to contribute, hope you're familiar with the Jekyll framework, its fine even if you're not. You can join our [slack channel](https://devbae.slack.com) to ease further communication and we can have a virtual meeting to discuss it further.
