### ISSUE TITLE
Put blogs in reverse chronological order

### ISSUE THREAD

**Issue by me-ydv-5** [devbae/devbae-blog#30]
I think it'll be better to just show the latest blog on top than the earliest one. We can also add a sort (by date) button for this.

**Comment by aroralakshya** [comment]
I was thinking that maybe we could use cookies to show the blogs based on tags.

**Comment by me-ydv-5** [comment]
How will that work? I think I missed your point. Going forward we might have so many blogs that a single page won't be sufficient so we'll need to group them and so the groups should be having blogs sorted on dates.

**Comment by aashish-ak** [comment]
@me-ydv-5  The articles are in reverse chronological order on the **Posts** page, this currently visible is the temporary homepage which is being worked upon, I and priyam are having a discussion about the homepage on [slack](https://devbae.slack.com), would be glad if you could join the conversation there. We're planning of creating a page containing featured posts there. @aroralakshya can you throw more light on the cookies thing that you were telling about, I'm keen to know more.

**Comment by me-ydv-5** [comment]
Alright then. Sounds good.
