### ISSUE TITLE
Smooth scroll

### ISSUE THREAD

**Issue by Signior-X** [devbae/devbae-blog#36]
**Is your feature request related to a problem? Please describe.**
When the user clicks on the content table, it directly takes the user to that heading, it does not feel much good.

**Describe the solution you'd like**
I would like to suggest the idea of smooth scroll, where it will animate and takes the user to the block with a motion smoothly.

**Describe alternatives you've considered**
There can be a css solution and a javascript solution for this thing.

**Additional context**

**Comment by Signior-X** [comment]
If possible, I want to do this issue if you found relevant, we can talk more on slack about this.

**Comment by aashish-ak** [comment]
Sure @Signior-X , If you think this is an improvement, then we can discuss it on slack further :v:
