### ISSUE TITLE
Change Markdown renderer from redcarpet to kramdown.

### ISSUE THREAD

**Issue by aashish-ak** [devbae/devbae-blog#8]
# Bug Report

The markdown renderer needs to be changed from `redcarpet` to `kramdown`, gh-pages does not support `redcarpet`, on which our blog is hosted.

## Description

The GitHub renderer should be made to `kramdown` including support of GFM (Github flavored markdown). As many markdown features like no_intra_emphasis, fenced_code_blocks, autolink, strikethrough, superscript would be gone with `redcarpet` gem. These features should be added with kramdown.

## Screenshots, if any

![redcarpet](https://user-images.githubusercontent.com/21988675/81454982-60577180-91ab-11ea-9f11-6063f732f916.png)

**Comment by aroralakshya** [comment]
I'm working on this.

**Comment by aashish-ak** [comment]
This issue is closed with #26 PR.
